version: "3.8"

services:
<<<<<<< HEAD
  frontend:
    container_name: tracer-frontend-prod
    image: tracer-frontend-prod
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - config/env/.env
    prots:
      - "8080:8080"
=======
  react-app:
    container_name: front-end-prod-container
    image: front-end-prod-image
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
>>>>>>> master
