version: "3.8"

services:
  frontend:
    image: tracer-frontend-dev
    container_name: tracer-frontend-dev
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - config/env/dev.env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src