version: "3.8"

services:
  frontend:
    container_name: letswatch-frontend-prod
    image: letswatch-frontend-prod
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - config/env/.env
    prots:
      - "8080:8080"
